### PR TITLE
Fuzzy search added using StringDistance.jl

### PR DESCRIPTION
**Pull request by raiutkarsh09**
Sorry I had to delete my old brach for some reason,
I've used StringDistance.jl for the fuzzy searching of snippets this time.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Thanks, @raiutkarsh09. Can you add some tests?

**Comment by raiutkarsh09** [comment]
I'm still quite unaware for how to do it but I'll still try my best

**Comment by abelsiqueira** [comment]
You can look into the `test/runtests.jl` file for examples. Essentially we want to make sure that we ask of the function returns what we expect. So `jet_pkg("datafarmes")` should return the same as `jet_pkg("DataFrames")` - possibly with some message on the match level?

**Comment by raiutkarsh09** [comment]
Sorry for being inactive for this time,
I have added few tests, please verify and do let me know if there are any changes!

**Comment by abelsiqueira** [comment]
Just passing by to apologize for the long time I'm taking to review this.

**Comment by abelsiqueira** [comment]
I'm sorry that this took so long. Thanks for the help.

**Comment by abelsiqueira** [comment]
@all-contributors please add @raiutkarsh09 for code

**Pull request merged**
